services:
#    esgis_gabon_post.example:
#        class: ESGISGabon\PostBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    prepersist.listener:
        class:    ESGISGabon\PostBundle\Listener\PersistPost
        arguments:
            - @blu_es_core.string_helper
        tags:
            - { name: doctrine.event_listener, event: prePersist}

    blu_es_post.type.corporate_post:
        class:    ESGISGabon\PostBundle\Form\CorporatePostType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: esgisgabon_postbundle_corporatepost}
