imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
        form:
            resources:
                - 'VichUploaderBundle:Form:fields.html.twig'
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        #auto_mapping: true
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    numeric_functions:
                        is_null:    BluEstuary\CoreBundle\Doctrine\MySQL\IsNull

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Stof\DoctrineExtension Conf
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true
            tree: true

# FOS User Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ESGISGabon\UserBundle\Entity\User

# FOS Rest Configuration
fos_rest:
    routing_loader:
        default_format:     json
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        templating_formats:
            json: false

#FPN Conf
fpn_tag:
    model:
        tag_class:      ESGISGabon\PostBundle\Entity\Keyword
        tagging_class:  ESGISGabon\PostBundle\Entity\KeywordTagging

#BluEs Conf
blu_estuary_post:
    model:
        category_class: ESGISGabon\PostBundle\Entity\Category

#Knp Gaufrette Conf
knp_gaufrette:
    stream_wrapper: ~
    adapters:
        esgis_ga_adapter:
            local:
                directory: %kernel.root_dir%/../web/files
    filesystems:
        esgis_ga_filesystem:
            adapter: esgis_ga_adapter

#VichUploader
vich_uploader:
    db_driver: orm
    storage:   gaufrette
    mappings:
        media_gallery:
            uri_prefix:         /files
            upload_destination: esgis_ga_filesystem
            namer:              vich_uploader.namer_uniqid
            directory_namer:    blu_es_media.directory_namer

#Liip Imagine
liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix:   files/cache
    filter_sets:
        thumbnail:
            quality: 80
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        small:
            quality: 85
            filters:
                thumbnail: { size: [150, 150], mode: outbound}
        medium:
            quality: 85
            filters:
                thumbnail: { size: [300, 300], mode: outbound}
        large:
            quality: 85
            filters:
                thumbnail: { size: [640, 640], mode: outbound}
        full:
            quality: 85
            filters:
                thumbnail: { size: [1280, 1280], mode: outbound}